version: '3.8'

services:
  app:
    build: .
    container_name: crypto-dashboard-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    networks:
      - crypto-network
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - crypto-network
    ports:
      - "6379:6379"

  # Opcional: Banco de dados local para desenvolvimento
  # db:
  #   image: postgres:15-alpine
  #   container_name: postgres-db
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER:-postgres}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - POSTGRES_DB=${POSTGRES_DB:-crypto_dashboard}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - crypto-network

networks:
  crypto-network:
    driver: bridge

volumes:
  redis_data:
  # postgres_data:  # Descomente se for usar o banco de dados local
