name: Atualização de Dados de Criptomoedas

on:
  schedule:
    # Executa a cada 15 minutos
    - cron: '*/15 * * * *'
  # Permite acionamento manual
  workflow_dispatch:

jobs:
  atualizar-dados:
    name: Atualizar Dados
    runs-on: ubuntu-latest
    
    steps:
    - name: Fazer checkout do repositório
      uses: actions/checkout@v3
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install python-dotenv
        
    - name: Executar script de atualização
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      run: |
        python scripts/update_data.py
